name: ML Pipeline

on: [push]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install dvc dvc-s3 pandas scikit-learn

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
        aws configure set region us-east-1

    - name: Pull dataset from DVC
      run: dvc pull

    - name: Train model
      run: python src/train.py

    - name: Upload metrics
      uses: actions/upload-artifact@v4
      with:
        name: metrics
        path: metrics.json

    - name: Build Docker Image
      run: docker build -t 2022bcs0025pranathi/housing .

    - name: Login DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u 2022bcs0025pranathi --password-stdin

    - name: Push Docker image
      run: docker push 2022bcs0025pranathi/housing
